# Generated by Django 3.1.1 on 2020-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='moodlevel',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
