# Generated by Django 3.1.1 on 2020-09-25 12:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_mood_moodlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mood',
            name='moodlevel',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
