# Generated by Django 3.1.1 on 2020-09-25 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0005_remove_mood_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
