# Generated by Django 3.1.1 on 2020-09-29 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0008_auto_20200928_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='mood',
            name='moodlevel',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
