# Generated by Django 3.1.1 on 2020-09-29 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0010_auto_20200929_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
